spring.application.name=customer-support-hub
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

app.jwt.secret=change-this-to-a-very-long-random-secret-key-with-at-least-32-characters
app.jwt.issuer=customer-support-hub
app.jwt.access-token-expiration-minutes=60

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE