spring.application.name=customer-support-hub

spring.datasource.url=jdbc:mysql://mysql-customer-support-hub-dudiilous-517e.h.aivencloud.com:24634/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_PLEUYNIS985pSE5yE5U
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.h2.console.enabled=true

app.jwt.secret=12345678901234567890123456789012
app.jwt.issuer=customer-support-hub
app.jwt.access-token-expiration-minutes=60

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE